# Copyright (c) 2015 Eayun, Inc.
# All rights reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

from alembic import op


# This needs manually dropping the existing foreign key constraints by
# executing "ALTER TABLE `table_name` DROP FOREIGN KEY `constraint_name`;".
# The constraint names are generated by the database automatically because
# in qos_init_ops.py we didn't specify the names. The constraint names could
# be found via "SHOW CREATE TABLE table_name".
# We have to do the aforementioned hack before this upgrade because by now
# I DON'T know how to do this with alembic.
def upgrade():
    op.create_foreign_key(
        'fk-eayun_qoss-port_id-ports',
        'eayun_qoss', 'ports', ['port_id'], ['id'],
        ondelete='SET NULL')
    op.create_foreign_key(
        'fk-eayun_qoss-router_id-routers',
        'eayun_qoss', 'routers', ['router_id'], ['id'],
        ondelete='SET NULL')
    op.create_foreign_key(
        'fk-eayun_qosqueues-qos_id-eayun_qoss',
        'eayun_qosqueues', 'eayun_qoss', ['qos_id'], ['id'],
        ondelete='CASCADE')
    op.create_foreign_key(
        'fk-eayun_qosqueues-parent_id-eayun_qosqueues',
        'eayun_qosqueues', 'eayun_qosqueues', ['parent_id'], ['id'],
        ondelete='CASCADE')
    op.create_foreign_key(
        'fk-eayun_qosfilters-qos_id-eayun_qoss',
        'eayun_qosfilters', 'eayun_qoss', ['qos_id'], ['id'],
        ondelete='CASCADE')
    op.create_foreign_key(
        'fk-eayun_qosfilters-queue_id-eayun_qosqueues',
        'eayun_qosfilters', 'eayun_qosqueues', ['queue_id'], ['id'],
        ondelete='SET NULL')


def downgrade():
    pass
